services:
  gmic_fl:
    build:
      context: .
      dockerfile: Dockerfile
    image: gmic-fl-nvflare
    container_name: gmic_fl_container
    volumes:
      - /mnt/srl-oahu-1/disk/home/lsollis/GMIC-FL:/workspace
      - /mnt/srl-oahu-1/disk/home/lsollis/data/XAI_output:/workspace/data/XAI_output
      - /mnt/srl-oahu-1/disk/home/lsollis/data/snapshots:/workspace/snapshots
      # Optional mounts for demo/testing - enable as needed
      # - ../GMIC-mods/data:/workspace/data
      # - ../GMIC-mods/demo/input_metadata.csv:/workspace/demo/input_metadata.csv
    ports:
      - "8888:8888"   # Jupyter Notebook (optional)
      - "5000:5000"   # Optional: FL API / Flask
    shm_size: "32gb"
    runtime: nvidia               # Required for GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true              # Keep stdin open for interaction
    tty: true                     # Allocate pseudo-TTY for shell
